/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysic;

import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.xml.bind.DatatypeConverter;

/**
 *
 * @author dell
 */
public class outputframe extends javax.swing.JFrame {
public String owt;    
public String filename;
Connection con=null;
ResultSet rs=null;
PreparedStatement pat=null;
    /**
     * Creates new form outputframe
     */
    public outputframe() {
        initComponents(); con=Connect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outhex = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        outhex.setColumns(20);
        outhex.setRows(5);
        jScrollPane1.setViewportView(outhex);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(51, 0, 0));
        jLabel1.setFont(new java.awt.Font("Rage Italic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("Possible Hexcode");
        jLabel1.setOpaque(true);

        lab.setBackground(new java.awt.Color(51, 0, 0));
        lab.setFont(new java.awt.Font("Mistral", 0, 24)); // NOI18N
        lab.setForeground(new java.awt.Color(255, 204, 102));
        lab.setText("File Name");
        lab.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lab.setText(filename);
        
        outhex.append(owt+"\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*\n*");  //only 8 character filename
              
        
        /*
    int m=0;
    mem[m]=startadress;
   // System.out.println("start address = "+startadress+"\n");
    //System.out.println("mem[0] = "+mem[m]+"\n");
    
   // String lines[], label[], x[];
        lines = inputext.split("\\r?\\n");
        int noflines = lines.length;
        ArrayList conv = new ArrayList();
        ArrayList pcon = new ArrayList();
        //System.out.println("Fine1");
        int i1=0;
        for(int i = 0;i<noflines; i++)
        {
            
            String[] words=lines[i].split("\\s");//splits the string based on whitespace  
            int num=words.length;
            System.out.println("\n\t"+num+"\n");
            for(String w:words)
            { 
                outhex.append(mem[m]);
                t1=t;
               //System.out.println("Fine2");
                sql = "SELECT opcode FROM opcode WHERE Mnemonic='"+w+"';";
               try {
                         Statement st=null;
                         st= con.createStatement();
                          ResultSet rs;
                          rs = st.executeQuery(sql);
                    System.out.println("Fine3");
                   
                    while(rs.next())
                    t= rs.getString(1);
                 //need to calculate memory alag se first.......................................  
          //  System.out.println(w+"  "+t);  
          if(t!=t1) 
          outhex.append(" "+t+"\n");
          else
          {
          for(int j=0; j<=i1;i1++)
              if(conv.get(j)==t)
                  continue;
               else
              {
                  
                  conv.set(i1++, t);
                  //pcon.set(i1, val);
              }
          }
System.out.println("Fine4");
            } 
               catch (Exception E) 
                    {
                        System.out.println("FAULT SEEN!");
                    }
                  // add 3 bytes to memory by default
                 // int a = Integer.parseInt(mem[m], 16);
                 int a=Integer.decode(mem[m]); 
                // System.out.println("mem[m] = "+mem[m]+"\n integer of it:"+a+"\n");
                  a=a+3;
                 // System.out.println(a+"\n");
                  mem[++m] = "0x"+Integer.toHexString(a);
                  //System.out.println(mem[m]+"\n");
    
    }//GEN-LAST:event_formWindowActivated
    }
        */
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outputframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outputframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab;
    private javax.swing.JTextArea outhex;
    // End of variables declaration//GEN-END:variables
}
